apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - namespace.yaml
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.4.0
    releaseName: mctc
    namespace: ingress-nginx
    valuesInline:
      controller:
        extraArgs:
          enable-ssl-passthrough: true
        hostNetwork: true
        ingressClassResource:
          default: true
        publishService:
          enabled: false
        reportNodeInternalIp: true
        service:
          type: NodePort
        watchIngressWithoutClass: true
