apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: gateway-manifest
  namespace: "$CLUSTER_NAMESPACE"
spec:
  workload:
    manifests:
    - apiVersion: gateway.networking.k8s.io/v1beta1
      kind: Gateway
      metadata:
        name: istio
        namespace: "$APP_NAMESPACE"
        labels:
          istio: ingressgateway
      spec:
        gatewayClassName: istio
        listeners:
        - name: default
          port: 80
          protocol: HTTP
          hostname: "$APP_HOST"
          allowedRoutes:
            namespaces:
              from: All
