apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: example
  namespace: default
spec:
  predicates:
  - requiredClusterSelector:
      claimSelector: {}
      labelSelector:
        matchExpressions: []
  prioritizerPolicy:
    mode: Additive